[versions]
agp = "8.13.0"
browser = "1.10.0"
kotlin = "2.3.21"
android-minSdk = "24"
android-compileSdk = "37"
startupRuntime = "1.2.0"

[libraries]
browser = { module = "androidx.browser:browser", version.ref = "browser" }
startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }